<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Shared</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Kernel" />
        <InternalsVisibleTo Include="Engine" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Sdk\Sdk.csproj" />
    </ItemGroup>

</Project>
