<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Razor.Shared</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Razor.Kernel" />
        <InternalsVisibleTo Include="Razor.Engine" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Razor.Sdk\Razor.Sdk.csproj" />
    </ItemGroup>

</Project>
